id: P009445
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:09.065159
source_metadata:
  id: bdr:W8LS20579
  title: རིན་པི་ཧྲིའི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    9b4898bc0b074a629ab0035b9d0af933:
      image_group_id: I8LS20581
      title: ''
      volume_number: 1
      total_pages: 381
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
