id: P009445
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20579
  title: རིན་པི་ཧྲིའི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    9b4898bc0b074a629ab0035b9d0af933:
      image_group_id: I8LS20581
      title: ''
      volume_number: 1
      total_pages: 381
      base_file: v001.txt
